name: Setup
description: Setup node, nx and install

runs:
  using: composite
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: "npm"

    - name: install
      shell: bash
      run: npm ci

    - uses: ./.github/actions/nx-setup
