name: Release
on:
  push:
    branches-ignore:
      - main
  pull_request: {}

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: build
        run: npm run affected -- -t build

      - name: test
        run: npm run affected -- -t lint test
